apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fileverse-storage-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: fileverse-storage
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 2  # Maximum number of pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale when average CPU usage exceeds 70%