apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-fileverse-storage-development-env-file
  namespace: fileverse-storage
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "development/fileverse-storage/.env"
        objectType: "secretsmanager"
        objectAlias: ".env"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-indexer-production-env-file
  namespace: fileverse-storage
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "production/fileverse-storage/.env"
        objectType: "secretsmanager"
        objectAlias: ".env"