function isCompleted() { return true };

module.exports = {
  tasks: [
    {
      taskId: "PRIVATE_KEY_DOWNLOAD",
      name: "Download your private keys",
      activityType: "CLIENT",
      points: 50,
      completed: isCompleted,
      type: "SECURITY",
      category: "DISCOVERY",
    },
    {
      taskId: "PUBLISH_PUBLIC_DDOC",
      name: "Publish a public dDoc",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "PUBLISH",
      category: "DISCOVERY",
    },
    {
      taskId: "PUBLISH_PRIVATE_WHITEBOARD",
      name: "Publish a private whiteboard",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "PUBLISH",
      category: "DISCOVERY",
    },
    {
      taskId: "PUBLISH_PUBLIC_DPAGE",
      name: "Publish a public dPage",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "PUBLISH",
      category: "DISCOVERY",
    },
    {
      taskId: "UPLOAD_PRIVATE_FILE",
      name: "Upload a private file",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "UPLOAD",
      category: "DISCOVERY",
    },
    {
      taskId: "UPLOAD_PUBLIC_FILE",
      name: "Upload a public file",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "UPLOAD",
      category: "DISCOVERY",
    },
    {
      taskId: "CHAT_ON_FILE",
      name: "Use chat on a file",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "CHAT",
      category: "DISCOVERY",
    },
    {
      taskId: "INVITE_PORTAL_COLLABORATOR",
      name: "Invite a collaborator to a portal",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "GROUP",
      category: "DISCOVERY",
    },
    {
      taskId: "TRY_LIVE_COLLABORATION",
      name: "Try a live collaboration",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "SHARE",
      category: "DISCOVERY",
    },
    {
      taskId: "PARTICIPATE_PORTAL_CHAT",
      name: "Participate in a portal chat",
      activityType: "CLIENT",
      points: 10,
      completed: isCompleted,
      type: "CHAT",
      category: "DISCOVERY",
    },
    {
      taskId: "CREATE_PUBLISH_3_DPAGES",
      name: "Create and publish 3 DPages",
      activityType: "AUTO",
      points: 25,
      completed: isCompleted,
      type: "CREATE",
      category: "ACHIEVEMENT",
    },
    {
      taskId: "OWN_ENS_DOMAIN",
      name: "Own a ENS Domain",
      activityType: "AUTO",
      points: 50,
      completed: isCompleted,
      type: "ENS",
      category: "ONCHAIN",
    },
  ],
};
